### ISSUE TITLE
Error when uploading an empty excel file using SampleWebApp

### ISSUE THREAD

**Issue by liamwang** [VahidN/EPPlus.Core#38] opened 2017-11-28 08:21 UTC
# Summary of the issue

It thrown an error when I created an new excel file with Office 2013 and uploaded it using SampleWebApp.  I opened the excel file and filled something, then run it again, it ran well.

## Environment

```
The in-use version: 1.5.2
Operating system: Win10 RS3
IDE: Visual Studio 2017
```

## Example code/Steps to reproduce:

```csharp
public async Task<IActionResult> FileUpload(IFormFile file)
{
	if (file == null || file.Length == 0)
	{
		return RedirectToAction("Index");
	}

	using (var memoryStream = new MemoryStream())
	{
		await file.CopyToAsync(memoryStream).ConfigureAwait(false);

		using (var package = new ExcelPackage(memoryStream))
		{
			var worksheet = package.Workbook.Worksheets[1]; // Tip: To access the first worksheet, try index 1, not 0
			return Content(readExcelPackageToString(package, worksheet));
		}
	}
}
```

## Full Stack trace:
![qq 20171128162343](https://user-images.githubusercontent.com/5000396/33309129-06c9a57e-d458-11e7-9e9a-64524e8fc326.png)

## Test file
[test.xlsx](https://github.com/VahidN/EPPlus.Core/files/1508967/test.xlsx)

**Comment by VahidN** [comment] 2017-11-29 11:10
The problem is the date of your entries in the final .zip/.xlsx file. its dataSize is 4 for your file, [but it seems it should be 32](https://github.com/VahidN/EPPlus.Core/blob/9db72234ea169bae69a0a1d07179a39bd5ff525e/src/EPPlus.Core/Packaging/DotNetZip/ZipEntry.Read.cs#L753):
```csharp
if (dataSize != 32)
throw new BadReadException(String.Format("  Unexpected size (0x{0:X4}) for NTFS times extra field at position 0x{1:X16}", dataSize, posn));
```
But if I remove this check, your file can be processed without any problems.
It's better to report your issue [here](https://github.com/JanKallman/EPPlus/issues).

**Comment by VahidN** [comment] 2017-11-30 06:23
Fixed via #https://github.com/VahidN/EPPlus.Core/commit/5de693d70298a18024b9c53767a41a9aa7e7f273
Try V1.5.4

**Closed as completed by VahidN** 2017-11-30 06:23 UTC

**Comment by liamwang** [comment] 2017-12-05 07:29
@VahidN That's really helpfull. Thank you for everything you've done.
